### ISSUE TITLE
After version 28.3, speed of blocks breaking slowed down considerably

### ISSUE THREAD

**Issue by donqixot** [portablejim/VeinMiner#36]
Since version 1.7.10_0.28.3, limit.block (default 800) and limit.radius (default 20) are not used from config file. I tested on large 4x4x20 structure (total 320 blocks) made out of vanilla iron ore. In version 30.2 (and every release since 28.3), I am not getting 320 iron ores at once using diamond pick with full hunger bar. Instead I am getting quantities like 58, 22, 37, 17, 31, 31, 12, 59 etc. I tried manually setting mode to "auto", reload config, manual set limit.blocks to 800 and radius to 20, doesn't help.

Anything changed since 28,3 in the way how radius is used?

**Comment by donqixot** [comment]
It looks like default value of 10 for
I:limit.blocksPerTick=10

is too low, when I raise it to 100, it works.

**Comment by donqixot** [comment]
Ok, I get it, it is not an issue or bug, it is a feature, like throttle. The longer you hold GRAVE key, the more blocks are destroyed. I normally held it for half the second, that's why I was getting 30 or 50 blocks at a time. Ok, really cool feature, I wish it was documented or mentioned somewhere. And thanks for really cool mod! I have another question, I will post it in a separate thread.

**Comment by donqixot** [comment]
After more testing, I see how this feature works, but speed of blocks breaking is way too slow for config settings. If limit.blocksPerTick=10, then to break 800 blocks I need 80 ticks, which is 4 seconds. In my testing, it takes at least 20 seconds to break 800 blocks (I tested on stone after white-listing them). Speed did change after version 28.3. Can you verify that speed is correct?

**Comment by Blue64** [comment]
It's probably because it's a larger loop of code, as the block breaking will also stop if you switch off the tool, or if you have it set to sneaking (like I do), and then stop sneaking.

My guess is it's simply taking longer because it needs to check all those parameters, then get the `enchantments` to apply, then send the `block break` event while applying the `enchantments`.

It could also be slowed down by the speed of your computer or server, for example if you're running a Mob Farm nearby while sending 200 block breaks per second (10/tick), on top of the code for their pathing, AI, Entity, item drops (witches drop a TON), you're then adding on all of the block break events, along with spawning their items, and looping the Veinminer checks.

You can see how the list simply gets longer and longer. Eventually there comes a point where you must decide between convenience and speed, especially if the processing can't keep up. The upside to this mod is that it guarantees the block break event, even in spite of lag (`"I swear I broke that log 3 times!"`).

There's a few ways to monitor your Ticks Per Second.
- Forge Mod Loader adds a command, which by default is "`/tps`" unless it's changed in the config.
- Extra Utilities Mod adds a few commands that all begin with "`/xu_`", amongst which there's one not listed (perhaps more) when you cycle through available commands, this one would be "`/xu_tps`" which will add 3 groups of 2 numbers each to your top left of your screen, it will always display the worst result in it's recent history for it's second number in these groups, though I'm not sure the specifics of what each group tracks. The middle group is the `average` if I'm not mistaken, you'll probably want the first group though.

And of course there's a few other ways available, but I'm not familiar enough with them to even know their name `^_^'` I know there's some programs that can do it.

**Comment by portablejim** [comment]
It should be faster now (0.13.0)

**Comment by donqixot** [comment]
Thank you very much, all good for a while now, after latest update.
