### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by FeistyPancake** [portablejim/VeinMiner#42]
I was playing around in my single player world with the new update, 0.31.0, and received this crash: http://pastebin.com/rg2vWM9g

**Comment by FeistyPancake** [comment]
The new update you posted did not fix the crash I got before. I am still getting it with 0.31.1.

**Comment by Soshi9** [comment]
the update  0.31.1  same crash: http://pastebin.com/xMT9yxfw

**Comment by TheXylis** [comment]
I'm getting the same crash in 0.31.1 on the Project Ozone mod pack in an RFtools dimension mining anything with a tinkers construct hammer http://paste.ubuntu.com/14885794/

I'm still getting the crash even if I set client.preferredMode=disabled in the configs 

Edit: Also only happens when holding shift

**Comment by bochen415** [comment]
same thing when a Extra Utilities Quarry is working and I'm in another dimension just doing my normal stuff
http://paste.ubuntu.com/15036725/
