### ISSUE TITLE
[1.10.2] Mod Rejections

### ISSUE THREAD

**Issue by Tencao** [portablejim/VeinMiner#95]
So several of my users have been getting constant mod rejections at random with the recent veinminer update (0.35.2). Some will be allowed on, some wont be and everyone has the same version as it's part of my modpack. There also is no log outside of the mod rejection. 

Forge version - 1.10.2 - 12.18.3.2185

**Comment by tenten8401** [comment]
Can second this.

**Comment by YOYOK9** [comment]
I am getting this issue as well. Very annoying. Only thing that seems to fix it is the player must do completely log out of the client and relaunch the pack (Sometimes)

**Comment by portablejim** [comment]
I'm not sure how to even try to fix this. Since you say it is random, I'm guessing you don't have an easy way to reproduce it.

If you have client and server log lines of when it happens (of the mod rejection) I may be able to deduce what is going wrong.

**Comment by Tencao** [comment]
When I saw this happen, I noticed that the problem didn't go away unless either the client was restarted or the server was. Veinminer has been the only mod to experience this problem, and if it helps I was also using veinminer integration too, which did not experience the same problem. There was no logs at the time of dismissing from what I remember outside of the standard mod rejection.

**Comment by portablejim** [comment]
Having the mod rejection lines (with maybe a few of context) may give insight. But to have it be solved with just a restart is puzzling.

**Comment by portablejim** [comment]
I quickly added some extra logging to the mod comparison function. Use this file instead, then capture the logs on login: https://minecraft.curseforge.com/projects/veinminer/files/2394905

**Comment by YOYOK9** [comment]
Where do the logs save too? I added it client side and don't see anything in my logs. Or does it need to be both client and server side?

**Comment by YOYOK9** [comment]
Ok so one of my players got the error before I did and gave me his latest log.
Server latest: (when player joined)
https://pastebin.com/2L2yTy8w

Players logs:
https://pastebin.com/5Rkru9pr

Now something I notice while working with technic (before switching to curse) is that mods with a "+" symbol in the name don't agree very well when loaded client side vs server. Looking at the logs the 2 vein miners are the same however the plus sign is switched to a dash. Could it be minecraft doesn't like "+" signs and that's why there is a communication error between the client and the server? Just an idea to try? 
(both have +) 
VeinMiner-1.9-0.35.3.595+a46c1b0
veinminermodintegration-0.6.0-1.9.4r29+2f88da6

**Comment by TheRealLeftShark** [comment]
wny news on this?

**Comment by portablejim** [comment]
This bug is still puzzling me.

**Comment by YOYOK9** [comment]
> This bug is still puzzling me.

could it possibly be the + in the name? Cause when you look at the crashes there's no "+" in the mod name?

**Comment by TheRealLeftShark** [comment]
also its pretty easy to recreate by having 2 accounts join the server at the same time

**Comment by TheRealLeftShark** [comment]
ok i think YOKOK9 is right ive change both the server and client side mod names to just VeinMiner and i no longer get the issue

**Comment by x-kazumi** [comment]
So i just renamed my Veinminer (version number) to VeinMiner and suddenly i was able to join to the server. i only did it once idk if the bug will come back when i relog sometimes but i will tell you if. :3

**Comment by YOYOK9** [comment]
Any news on when an update will be for this? Seems like a pretty easy fix.

**Comment by portablejim** [comment]
I don't want to abandon semantic versioning.

**Comment by YOYOK9** [comment]
If you were to change the "+" to a "-" it should fix the issue. Since the servers seem to be registering the + as a - but the clients aren't.

**Comment by Tencao** [comment]
This is the only mod that has the version bug, and I know other mods also use version numbers in theirs so it might just be a simple case of formatting like @YOYOK9 said

**Comment by fabri2000779** [comment]
i change the mod name and it didnt work for me :(

**Comment by FrilledFish** [comment]
I can second what @fabri2000779 said. It does not help changing the mod name. A temp fix is restarting the server, but it is impossible to time it as it is random when it occurs. This was done on a server with multiple people and it worked for none. This was tested by both changing it on the server and via the clients. Neither helped.

**Comment by fabri2000779** [comment]
@FrilledFish i think i have a solution, i do the following: i delete the mod(veinminer), download it on curse website and put it back to the server and rember remove the config. That fix the server for me, so the solution is re-install the mod(like i said this works for me) and i didnt change the name so appear that this "+" dont affect the server, anyway sorry for my bad english

**Comment by FrilledFish** [comment]
@fabri2000779 I have tried and it didn't seem like it worked. I will try later and see if I get better results. I don't think I delete the config, which might seem like the problem.
Edit: And yes, I don't think the name has anything to do with it.

**Comment by fabri2000779** [comment]
@portablejim why you didnt fix this bug yet, what are you waiting to fix this?

**Comment by portablejim** [comment]
@fabri2000779 I'm waiting to get a clear understanding of what exactly is wrong. I don't want to work by trying to fix bugs by some magic incantation. And anyway, the magic solution of changing the name seems to not work anyway (by both your comments and FrilledFish's comments)

Continuning the investigation, dose the server you are having the problem on also have sponge?

**Comment by FrilledFish** [comment]
@portablejim This has occurred on our server which is currently running sponge.

To my knowledge, servers without sponge also have this problem, but sadly I can only confirm it happens on sponge servers.

**Comment by fabri2000779** [comment]
@portablejim yeah my server (foolcraft) have sponge

**Comment by YOYOK9** [comment]
@portablejim my servers do as well. Sponge seems to be the new common for most servers.

**Comment by phit** [comment]
could this be caused by the `canBeDeactivated = true` in the `@Mod` annotation?

**Comment by heyoomimi** [comment]
It appears that a server restart allows players to rejoin.

**Comment by dualspiral** [comment]
@portablejim I've just been investigating the issue on the Sponge end, and it turns out to be a thread safety problem, which is exaserbated by Sponge for various reasons - I'll try to deal with this on the Sponge side (there is something Sponge is doing which breaks this a lot more), but it's important to note that this could theroretically happen without Sponge too.

[The offending line is here](https://github.com/portablejim/VeinMiner/blob/1.9/src/main/java/portablejim/veinminer/VeinMiner.java#L108). `getActiveContainer` is effectively not thread safe - **and this line is called off the server thread**. If there are no events being fired on the server thread, this is usually fine (Sponge can do some weird things, but in itself, that's a bug), because FML then uses the call stack to work out what's calling the method and can retrieve the right mod.

**However**, when an event is be being fired on the main thread, FML (and Sponge) can explicity set a mod (or plugin) to be returned by `getActiveContainer()`. If someone is logging in with VeinMiner whilst an event is being fired, (FML or Sponge), `getActiveContainer()` will return the mod _currently handling the event_. So, you'll get the wrong mod, the wrong version, and you'll throw out the client.

Rather than rely on `getActiveContainer()`, you should get the version out of using `Loader.instance().getIndexedModList().get("VeinMiner")` (or the lowercase form for 1.11.x) - this should solve the issue on your end.

**Comment by dualspiral** [comment]
FYI: this is solved in Sponge (https://github.com/SpongePowered/SpongeForge/issues/1460), users having this problem should update to the latest SpongeForge, but I still recommend that you swap out `getActiveContainer()`.

**Comment by portablejim** [comment]
Reopen if a problem again.
